[package]
name = "shooter3d"
version = "0.1.0"
edition = "2021"

[dependencies]
geo = "0.28.0"
macroquad = "0.4.13"
rayon = "1.10.0"
serde = {version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

